/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evet.managment.system;

/**
 *
 * @author Dewanganii
 */
public class Anniversaries extends javax.swing.JFrame {

    /**
     * Creates new form Anniversaries
     */
    public Anniversaries() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<String>();
        label3 = new java.awt.Label();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        label4 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        jTextField3 = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        label8 = new java.awt.Label();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 51, 0));
        label1.setText("Anniversaries");
        getContentPane().add(label1);
        label1.setBounds(110, 50, 310, 46);

        label2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label2.setText("Type");
        getContentPane().add(label2);
        label2.setBounds(120, 180, 50, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 180, 190, 30);

        label3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label3.setText("Date");
        getContentPane().add(label3);
        label3.setBounds(120, 250, 60, 25);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 250, 190, 30);

        label4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label4.setText("Time");
        getContentPane().add(label4);
        label4.setBounds(120, 320, 60, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 320, 190, 30);

        label5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label5.setText("Hall Numbers");
        getContentPane().add(label5);
        label5.setBounds(120, 390, 140, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 380, 190, 30);

        label6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label6.setText("Phone Number");
        getContentPane().add(label6);
        label6.setBounds(120, 450, 150, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 440, 190, 30);

        label7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label7.setText("Menu");
        getContentPane().add(label7);
        label7.setBounds(120, 510, 80, 25);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Yes");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(280, 510, 49, 25);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("No");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(360, 510, 45, 25);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton1.setText("Search");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(430, 510, 90, 23);

        label8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label8.setText("Amount");
        getContentPane().add(label8);
        label8.setBounds(120, 570, 90, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(280, 560, 190, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Date", "Time", "Hall Number", "Phone Number", "Menu", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 170, 660, 90);

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setText("Insert");
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 300, 130, 40);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setText("Update");
        getContentPane().add(jButton2);
        jButton2.setBounds(810, 300, 130, 40);

        jButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        getContentPane().add(jButton3);
        jButton3.setBounds(960, 300, 120, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Go to the home page");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1100, 300, 180, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 1320, 650);

        setSize(new java.awt.Dimension(1338, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anniversaries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anniversaries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anniversaries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anniversaries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anniversaries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
